const express = require('express')
const router = express.Router()

const auth = require('./auth')
const users = require('./users')
const stores = require('./seller/stores')
const profiles = require('./customer/profiles')
const types = require('./seller/types')
const items = require('./seller/items')
const durations = require('./seller/durations')
const services = require('./customer/services')
const transactions = require('./transactions')
const sellerServices = require('./seller/services')
const report = require('./seller/reports')
const dashboard = require('./dashboard')
const items = require('../controller/api/v1/seller/items')

router.use('/api/v1', auth)
router.use('/api/v1', users)
router.use('/api/v1', stores)
router.use('/api/v1', profiles)
router.use('/api/v1', types)
router.use('/api/v1', items)
router.use('/api/v1', durations)
router.use('/api/v1', services)
router.use('/api/v1', transactions)
router.use('/api/v1', sellerServices)
router.use('/api/v1', report)
router.use('/api/v1', dashboard)

module.exports = router
